// <auto-generated />
namespace AFT.RegoV2.Infrastructure.DataAccess.Payment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IncreaseBankAccountNumberLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncreaseBankAccountNumberLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201604052322406_IncreaseBankAccountNumberLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
