// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(function(require) {
    return {
      bankIdMaxLength: 20,
      bankNameMaxLength: 50,
      remarksMaxLength: 200
    };
  });

}).call(this);
