// Generated by IcedCoffeeScript 108.0.9
(function() {
  var RegisterModel, model,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  RegisterModel = (function() {
    function RegisterModel() {
      this.submitRegistration = __bind(this.submitRegistration, this);
      this.firstName = ko.observable("").extend({
        validatable: true
      });
      this.lastName = ko.observable("").extend({
        validatable: true
      });
      this.email = ko.observable("").extend({
        validatable: true
      });
      this.phoneNumber = ko.observable("").extend({
        validatable: true
      });
      this.mailingAddressLine1 = ko.observable("").extend({
        validatable: true
      });
      this.mailingAddressCity = ko.observable().extend({
        validatable: true
      });
      this.mailingAddressStateProvince = ko.observable().extend({
        validatable: true
      });
      this.mailingAddressPostalCode = ko.observable("").extend({
        validatable: true
      });
      this.countryCode = ko.observable().extend({
        validatable: true
      });
      this.currencyCode = ko.observable().extend({
        validatable: true
      });
      this.captcha = ko.observable().extend({
        validatable: true
      });
      this.captchaCheck = ko.observable().extend({
        validatable: true
      });
      this.cultureCode = ko.observable().extend({
        validatable: true
      });
      this.username = ko.observable("").extend({
        validatable: true
      });
      this.password = ko.observable("").extend({
        validatable: true
      });
      this.passwordConfirm = ko.observable("").extend({
        validatable: true
      });
      this.dayOB = ko.observable(0).extend({
        validatable: true
      });
      this.monthOB = ko.observable(0).extend({
        validatable: true
      });
      this.yearOB = ko.observable(0).extend({
        validatable: true
      });
      this.title = ko.observable().extend({
        validatable: true
      });
      this.contactPreference = ko.observable().extend({
        validatable: true
      });
      this.securityQuestionId = ko.observable().extend({
        validatable: true
      });
      this.securityAnswer = ko.observable().extend({
        validatable: true
      });
      this.dateOfBirth = ko.computed((function(_this) {
        return function() {
          return _this.yearOB() + "/" + _this.monthOB() + "/" + _this.dayOB();
        };
      })(this)).extend({
        validatable: true
      });
      this.physicalAddressLine1 = ko.computed((function(_this) {
        return function() {
          return _this.mailingAddressLine1();
        };
      })(this)).extend({
        validatable: true
      });
      this.physicalAddressCity = ko.computed((function(_this) {
        return function() {
          return _this.mailingAddressPostalCode();
        };
      })(this)).extend({
        validatable: true
      });
      this.physicalAddressPostalCode = ko.computed((function(_this) {
        return function() {
          return _this.mailingAddressPostalCode();
        };
      })(this)).extend({
        validatable: true
      });
      this.brandId = ko.computed((function(_this) {
        return function() {
          return "00000000-0000-0000-0000-000000000138";
        };
      })(this)).extend({
        validatable: true
      });
      this.cultureCode = ko.computed((function(_this) {
        return function() {
          return findCookieValue("CultureCode");
        };
      })(this)).extend({
        validatable: true
      });
      this.gender = ko.computed((function(_this) {
        return function() {
          return $('input[name="Gender"]:checked').val();
        };
      })(this)).extend({
        validatable: true
      });
      this.over18 = ko.observable(false);
      this.acceptTerms = ko.observable(false);
    }

    RegisterModel.prototype.submitRegistration = function() {
      var serializedForm;
      serializedForm = $('#register-step1-form').serializeArray();
      serializedForm.push({
        name: "Gender",
        value: $('input[name="Gender"]:checked').val()
      }, {
        name: "PhoneNumber",
        value: $('#phone-number').intlTelInput("getNumber").replace('+', '00')
      }, {
        name: "CurrencyCode",
        value: "RMB"
      }, {
        name: "CountryCode",
        value: "CN"
      });
      return $.ajax({
        url: '/api/ValidateRegisterInfo',
        type: 'post',
        data: $.param(serializedForm)
      }).success((function(_this) {
        return function(response) {
          if (response.hasError) {
            return $.each(response.errors, function(propName) {
              var observable;
              observable = _this[propName];
              if (observable) {
                observable.error = i18n.t("apiResponseCodes." + response.errors[propName]);
                observable.__valid__(false);
                return observable.isModified(true);
              } else {
                return alert(response.errors[propName]);
              }
            });
          } else {
            return $.ajax({
              url: '/api/Register',
              type: 'post',
              data: $.param(serializedForm)
            }).success(function(response) {
              return redirect("/Home/RegisterStep2");
            }).fail(function() {
              return alert('Unexpected error occured.');
            });
          }
        };
      })(this));
    };

    return RegisterModel;

  })();

  model = new RegisterModel();

  ko.applyBindings(model, document.getElementById("register-wrapper"));

}).call(this);
