// Generated by IcedCoffeeScript 108.0.9
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(["i18next", "player-manager/send-new-password-dialog", "security/security", 'player-manager/change-vip-level-dialog', 'player-manager/change-payment-level-dialog', 'config'], function(i18n, dialog, security, dialogVip, dialogPaymentLevel, config) {
    var Account;
    return Account = (function() {
      function Account() {
        this.cancelExclusion = __bind(this.cancelExclusion, this);
        this.unlock = __bind(this.unlock, this);
        this.changeFreezeStatus = __bind(this.changeFreezeStatus, this);
        var self;
        self = this;
        this.firstName = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 50
        }).extend({
          pattern: {
            message: 'Invalid First Name',
            params: '^[A-Za-z0-9]+(?:[ .\'-][A-Za-z0-9]+)*$'
          }
        });
        this.lastName = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 20
        }).extend({
          pattern: {
            message: 'Invalid Last Name',
            params: '^[A-Za-z0-9]+(?:[ ._\'-][A-Za-z0-9]+)*$'
          }
        });
        this.dateOfBirth = ko.observable().extend({
          required: true
        });
        this.title = ko.observable();
        this.titles = ko.observable();
        this.gender = ko.observable();
        this.genders = ko.observable();
        this.email = ko.observable().extend({
          required: true,
          email: true,
          minLength: 1,
          maxLength: 50
        });
        this.phoneNumber = ko.observable().extend({
          required: true,
          number: true,
          minLength: 8,
          maxLength: 15
        });
        this.mailingAddressLine1 = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 50
        });
        this.mailingAddressLine2 = ko.observable().extend({
          maxLength: 50
        });
        this.mailingAddressLine3 = ko.observable().extend({
          maxLength: 50
        });
        this.mailingAddressLine4 = ko.observable().extend({
          maxLength: 50
        });
        this.mailingAddressCity = ko.observable();
        this.mailingAddressPostalCode = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 10
        });
        this.mailingAddressStateProvince = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 20
        });
        this.physicalAddressLine1 = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 50
        });
        this.physicalAddressLine2 = ko.observable().extend({
          maxLength: 50
        });
        this.physicalAddressLine3 = ko.observable().extend({
          maxLength: 50
        });
        this.physicalAddressLine4 = ko.observable().extend({
          maxLength: 50
        });
        this.physicalAddressCity = ko.observable();
        this.physicalAddressPostalCode = ko.observable().extend({
          required: true,
          minLength: 1,
          maxLength: 10
        });
        this.physicalAddressStateProvince = ko.observable();
        this.securityQuestion = ko.observable();
        this.securityAnswer = ko.observable();
        this.country = ko.observable();
        this.countryName = ko.computed(function() {
          var country;
          country = self.country();
          if (country) {
            return country.name();
          } else {
            return null;
          }
        });
        this.countries = ko.observableArray();
        this.contactPreference = ko.observable();
        this.contactMethods = ko.observable();
        this.accountAlertEmail = ko.observable(false);
        this.accountAlertSms = ko.observable(false);
        this.accountAlertsText = ko.computed((function(_this) {
          return function() {
            var text;
            text = [];
            if (_this.accountAlertEmail()) {
              text.push("Email");
            }
            if (_this.accountAlertSms()) {
              text.push("Sms");
            }
            if (text.length > 0) {
              return text.join(", ");
            } else {
              return "None";
            }
          };
        })(this)).extend({
          validation: {
            validator: (function(_this) {
              return function() {
                return _this.accountAlertEmail() || _this.accountAlertSms();
              };
            })(this),
            message: i18n.t("app:playerManager.error.accountAlertsEmpty"),
            params: true
          }
        });
        this.marketingAlertEmail = ko.observable();
        this.marketingAlertSms = ko.observable();
        this.marketingAlertPhone = ko.observable();
        this.marketingAlertsText = ko.computed((function(_this) {
          return function() {
            var text;
            text = [];
            if (_this.marketingAlertEmail()) {
              text.push("Email");
            }
            if (_this.marketingAlertSms()) {
              text.push("Sms");
            }
            if (_this.marketingAlertPhone()) {
              text.push("Phone");
            }
            if (text.length > 0) {
              return text.join(", ");
            } else {
              return "None";
            }
          };
        })(this)).extend({
          validation: {
            validator: (function(_this) {
              return function() {
                return _this.marketingAlertEmail() || _this.marketingAlertSms() || _this.marketingAlertPhone();
              };
            })(this),
            message: i18n.t("app:playerManager.error.accountAlertsEmpty"),
            params: true
          }
        });
        this.paymentLevel = ko.observable();
        this.paymentLevels = ko.observableArray();
        this.paymentLevelName = ko.computed(function() {
          var level;
          level = self.paymentLevel();
          if (level) {
            return level.name();
          } else {
            return null;
          }
        });
        this.registrationDate = ko.observable();
        this.licensee = ko.observable();
        this.brand = ko.observable();
        this.currency = ko.observable();
        this.culture = ko.observable();
        this.vipLevel = ko.observable();
        this.vipLevels = ko.observableArray();
        this.vipLevelCode = ko.computed(function() {
          var vipLevel;
          vipLevel = self.vipLevel();
          if (vipLevel) {
            return vipLevel.code();
          } else {
            return null;
          }
        });
        this.vipLevelName = ko.computed(function() {
          var vipLevel;
          vipLevel = self.vipLevel();
          if (vipLevel) {
            return vipLevel.name();
          } else {
            return null;
          }
        });
        this.playerId = ko.observable();
        this.detailsEditMode = ko.observable(false);
        this.fullName = ko.observable();
        this.username = ko.observable();
        this.frozen = ko.observable();
        this.freezeButtonText = ko.computed((function(_this) {
          return function() {
            if (_this.frozen() === true) {
              return "Unfreeze";
            } else {
              return "Freeze";
            }
          };
        })(this));
        this.isLocked = ko.observable();
        this.isInactive = ko.observable();
        this.isSelfExcluded = ko.observable();
        this.isTimedOut = ko.observable();
        this.isEditBtnVisible = ko.computed(function() {
          return security.isOperationAllowed(security.permissions.update, security.categories.playerManager);
        });
        this.isSetStatusBtnVisible = ko.computed(function() {
          var isActivated;
          isActivated = !self.isInactive();
          return !isActivated && security.isOperationAllowed(security.permissions.activate, security.categories.playerManager) || isActivated && security.isOperationAllowed(security.permissions.deactivate, security.categories.playerManager);
        });
        this.activateButtonText = ko.computed(function() {
          if (!self.isInactive()) {
            return "Deactivate";
          } else {
            return "Activate";
          }
        }, this);
        this.unexcludeButtonText = ko.computed(function() {
          if (self.isSelfExcluded()) {
            return "Cancel exclusion";
          } else if (self.isTimedOut()) {
            return "Cancel time out";
          }
        }, this);
        this.canAssignVipLevel = ko.computed(function() {
          return security.isOperationAllowed(security.permissions.assignVipLevel, security.categories.playerManager);
        });
        this.canAssignPaymentLevel = ko.computed(function() {
          return security.isOperationAllowed(security.permissions.assignPaymentLevel, security.categories.playerManager);
        });
        this.initialData = {};
      }

      Account.prototype.activate = function(data) {
        var self;
        self = this;
        this.playerId(data.playerId);
        return $.get(config.adminApi("PlayerInfo/Get"), {
          id: this.playerId()
        }).done(function(data) {
          self.brandId = data.brandId;
          self.frozen(data.frozen);
          self.isLocked(data.isLocked);
          self.isInactive(data.isInactive);
          self.isSelfExcluded(data.isSelfExcluded);
          self.isTimedOut(data.isTimedOut);
          ko.mapping.fromJS(data, {}, self.initialData);
          self.registrationDate(data.dateRegistered);
          self.licensee(data.licensee);
          self.brand(data.brand);
          self.currency(data.currencyCode);
          self.culture(data.culture);
          $.ajax(config.adminApi("PlayerManager/GetAddPlayerData")).done(function(response) {
            return ko.mapping.fromJS(response.data, {}, self);
          });
          $.ajax(config.adminApi("Brand/GetCountries"), {
            async: false,
            data: {
              brandId: self.brandId
            },
            success: function(response) {
              var countries;
              ko.mapping.fromJS(response, {}, self);
              countries = self.countries();
              return $.each(countries, function(index, value) {
                if (value.code() === self.initialData.countryCode()) {
                  return self.initialData["country"] = ko.observable(value);
                }
              });
            }
          });
          $.ajax(config.adminApi("PlayerManager/GetVipLevels?brandId=" + self.brandId), {
            async: false,
            success: function(response) {
              var vipLevel;
              ko.mapping.fromJS(response, {}, self);
              vipLevel = ko.utils.arrayFirst(self.vipLevels(), function(thisVipLevel) {
                return thisVipLevel.id() === self.initialData.vipLevel();
              });
              return self.vipLevel(vipLevel);
            }
          });
          $.ajax(config.adminApi('PlayerInfo/GetPlayerTitle?id=' + self.playerId())).done(function(player) {
            self.fullName(player.firstName + " " + player.lastName);
            return self.username(player.username);
          });
          return $.ajax(config.adminApi("PlayerManager/GetPaymentLevels?brandId=" + self.brandId + "&currency=" + self.currency()), {
            success: function(response) {
              var paymentLevel;
              ko.mapping.fromJS(response, {}, self);
              paymentLevel = ko.utils.arrayFirst(self.paymentLevels(), function(thisPaymentLevel) {
                return thisPaymentLevel.id() === self.initialData.paymentLevel();
              });
              self.paymentLevel(paymentLevel);
              return self.setForm();
            }
          });
        });
      };

      Account.prototype.setForm = function() {
        this.firstName(this.initialData.firstName());
        this.lastName(this.initialData.lastName());
        this.dateOfBirth(this.initialData.dateOfBirth());
        this.title(this.initialData.title());
        this.gender(this.initialData.gender());
        this.email(this.initialData.email());
        this.phoneNumber(this.initialData.phoneNumber());
        this.mailingAddressLine1(this.initialData.mailingAddressLine1());
        this.mailingAddressLine2(this.initialData.mailingAddressLine2());
        this.mailingAddressLine3(this.initialData.mailingAddressLine3());
        this.mailingAddressLine4(this.initialData.mailingAddressLine4());
        this.mailingAddressCity(this.initialData.mailingAddressCity());
        this.mailingAddressPostalCode(this.initialData.mailingAddressPostalCode());
        this.mailingAddressStateProvince(this.initialData.mailingAddressStateProvince());
        this.physicalAddressLine1(this.initialData.physicalAddressLine1());
        this.physicalAddressLine2(this.initialData.physicalAddressLine2());
        this.physicalAddressLine3(this.initialData.physicalAddressLine3());
        this.physicalAddressLine4(this.initialData.physicalAddressLine4());
        this.physicalAddressCity(this.initialData.physicalAddressCity());
        this.physicalAddressPostalCode(this.initialData.physicalAddressPostalCode());
        this.physicalAddressStateProvince(this.initialData.physicalAddressStateProvince());
        this.country(this.initialData.country());
        this.contactPreference(this.initialData.contactPreference());
        this.accountAlertSms(this.initialData.accountAlertSms());
        this.accountAlertEmail(this.initialData.accountAlertEmail());
        this.marketingAlertSms(this.initialData.marketingAlertSms());
        this.marketingAlertEmail(this.initialData.marketingAlertEmail());
        this.marketingAlertPhone(this.initialData.marketingAlertPhone());
        this.securityQuestion(this.initialData.securityQuestion());
        return this.securityAnswer(this.initialData.securityAnswer());
      };

      Account.prototype.edit = function() {
        return this.detailsEditMode(true);
      };

      Account.prototype.cancelEdit = function() {
        this.setForm();
        return this.detailsEditMode(false);
      };

      Account.prototype.resendActivationEmail = function() {
        return $.ajax(config.adminApi('PlayerInfo/ResendActivationEmail'), {
          type: "post",
          data: ko.toJSON({
            id: this.playerId()
          }),
          contentType: 'application/json',
          success: function(response) {
            if (response.result === "success") {
              return alert("Activation Email sent!");
            } else {
              return alert("failed to resend activation email");
            }
          }
        });
      };

      Account.prototype.showSendMessageDialog = function(data) {
        var id, newPassword, sendBy;
        id = data.playerId;
        newPassword = '';
        sendBy = "Email";
        return dialog.show(this, id, newPassword, sendBy);
      };

      Account.prototype.setStatus = function() {
        var self;
        self = this;
        return $.ajax(config.adminApi('PlayerInfo/SetStatus'), {
          type: "post",
          data: ko.toJSON({
            id: self.playerId(),
            active: self.isInactive()
          }),
          contentType: "application/json",
          success: function(response) {
            if (response.result === "success") {
              return self.isInactive(!response.active);
            } else {
              return alert("Can't change status");
            }
          }
        });
      };

      Account.prototype.changeFreezeStatus = function() {
        return $.ajax(config.adminApi('PlayerInfo/SetFreezeStatus'), {
          type: "post",
          data: ko.toJSON({
            playerId: this.playerId(),
            freeze: !this.frozen()
          }),
          contentType: "application/json",
          success: (function(_this) {
            return function(response) {
              if (response.result !== "success") {
                return alert("Can't freeze/unfreeze account");
              } else {
                return _this.frozen(!_this.frozen());
              }
            };
          })(this)
        });
      };

      Account.prototype.unlock = function() {
        return $.ajax(config.adminApi('PlayerInfo/Unlock'), {
          type: "post",
          data: ko.toJSON({
            playerId: this.playerId()
          }),
          contentType: "application/json",
          success: (function(_this) {
            return function(response) {
              if (response.result !== "success") {
                return alert("Can't unlock the account");
              } else {
                return _this.isLocked(false);
              }
            };
          })(this)
        });
      };

      Account.prototype.cancelExclusion = function() {
        return $.ajax(config.adminApi('PlayerInfo/CancelExclusion'), {
          type: "post",
          data: ko.toJSON({
            playerId: this.playerId()
          }),
          contentType: "application/json",
          success: (function(_this) {
            return function(response) {
              if (response.result !== "success") {
                return alert("Can't cancel exlusion on the account");
              } else {
                _this.isSelfExcluded(false);
                return _this.isTimedOut(false);
              }
            };
          })(this)
        });
      };

      Account.prototype.showChangeVipLevelDialog = function(data) {
        var brand, currentVipLevel, id, userName, vipLevels;
        id = data.playerId();
        brand = data.brand();
        userName = data.username();
        currentVipLevel = data.vipLevelCode();
        vipLevels = data.vipLevels;
        return dialogVip.show(this, id, brand, userName, currentVipLevel, vipLevels);
      };

      Account.prototype.showChangePaymentLevelDialog = function(data) {
        var brand, currentPaymentLevel, id, licensee, paymentLevels;
        id = data.playerId();
        licensee = data.licensee();
        brand = data.brand();
        currentPaymentLevel = data.paymentLevel().id();
        paymentLevels = data.paymentLevels;
        return dialogPaymentLevel.show(this, id, licensee, brand, currentPaymentLevel, paymentLevels);
      };

      Account.prototype.clearEdit = function() {
        this.firstName("");
        this.lastName("");
        this.email("");
        this.phoneNumber("");
        this.mailingAddressLine1("");
        this.mailingAddressLine2("");
        this.mailingAddressLine3("");
        this.mailingAddressLine4("");
        this.mailingAddressCity("");
        this.mailingAddressPostalCode("");
        this.mailingAddressStateProvince("");
        this.physicalAddressLine1("");
        this.physicalAddressLine2("");
        this.physicalAddressLine3("");
        this.physicalAddressLine4("");
        this.physicalAddressCity("");
        this.physicalAddressPostalCode("");
        this.physicalAddressStateProvince("");
        this.accountAlertSms(false);
        this.accountAlertEmail(false);
        this.marketingAlertSms(false);
        this.marketingAlertEmail(false);
        return this.marketingAlertPhone(false);
      };

      Account.prototype.saveEdit = function() {
        var data, self;
        self = this;
        $(self.uiElement).parent().hide().prev().show();
        data = {
          PlayerId: this.playerId,
          FirstName: this.firstName(),
          LastName: this.lastName(),
          DateOfBirth: this.dateOfBirth(),
          Title: this.title(),
          Gender: this.gender(),
          Email: this.email(),
          PhoneNumber: this.phoneNumber(),
          MailingAddressLine1: this.mailingAddressLine1(),
          MailingAddressLine2: this.mailingAddressLine2(),
          MailingAddressLine3: this.mailingAddressLine3(),
          MailingAddressLine4: this.mailingAddressLine4(),
          MailingAddressCity: this.mailingAddressCity(),
          MailingAddressPostalCode: this.mailingAddressPostalCode(),
          MailingAddressStateProvince: this.mailingAddressStateProvince(),
          PhysicalAddressLine1: this.physicalAddressLine1(),
          PhysicalAddressLine2: this.physicalAddressLine2(),
          PhysicalAddressLine3: this.physicalAddressLine3(),
          PhysicalAddressLine4: this.physicalAddressLine4(),
          PhysicalAddressCity: this.physicalAddressCity(),
          PhysicalAddressPostalCode: this.physicalAddressPostalCode(),
          PhysicalAddressStateProvince: this.physicalAddressStateProvince(),
          CountryCode: self.country().code,
          ContactPreference: this.contactPreference(),
          AccountAlertEmail: this.accountAlertEmail(),
          AccountAlertSms: this.accountAlertSms(),
          MarketingAlertEmail: this.marketingAlertEmail(),
          MarketingAlertSms: this.marketingAlertSms(),
          MarketingAlertPhone: this.marketingAlertPhone(),
          PaymentLevelId: this.paymentLevel().id
        };
        return $.ajax({
          type: "POST",
          url: config.adminApi('PlayerInfo/Edit'),
          data: ko.toJSON(data),
          contentType: "application/json"
        }).done(function(response) {
          $(self.uiElement).parent().show().prev().hide();
          if (response.result === "success") {
            self.detailsEditMode(false);
            response.data = "app:players.updated";
            ko.mapping.fromJS(data, {}, self.initialData);
            return $("#player-grid").trigger("reload");
          }
        });
      };

      return Account;

    })();
  });

}).call(this);
