// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(function(require) {
    var ViewModel;
    require("controls/grid");
    return ViewModel = (function() {
      function ViewModel() {
        this.moment = require("moment");
        this.playerId = ko.observable();
        this.config = require("config");
        this.paymentMethods = ko.observableArrays()[0];
      }

      ViewModel.prototype.activate = function(data) {
        this.playerId(data.playerId);
        return $.get("/PaymentSettings/PaymenMethodsList").done((function(_this) {
          return function(response) {
            var item, _i, _len, _results;
            _results = [];
            for (_i = 0, _len = response.length; _i < _len; _i++) {
              item = response[_i];
              _results.push(_this.paymentMethods.push(item));
            }
            return _results;
          };
        })(this));
      };

      ViewModel.prototype.attached = function(view) {
        var $grid;
        $grid = findGrid(view);
        return $("form", view).submit(function() {
          $grid.trigger("reload");
          return false;
        });
      };

      return ViewModel;

    })();
  });

}).call(this);
