// Generated by IcedCoffeeScript 108.0.9
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function(require) {
    var Content, ContentMessage, i18n;
    ContentMessage = require("./content-message");
    i18n = require("i18next");
    return Content = (function() {
      function Content() {
        this.setLanguages = __bind(this.setLanguages, this);
        this.Id = ko.observable();
        this.Languages = ko.observableArray();
      }

      Content.prototype.setLanguages = function(languages) {
        var contentMessage, language, _i, _len, _results;
        this.Languages.removeAll();
        _results = [];
        for (_i = 0, _len = languages.length; _i < _len; _i++) {
          language = languages[_i];
          contentMessage = new ContentMessage(this.Id(), language.code(), language.name());
          this.Languages.push(contentMessage);
          _results.push(contentMessage.loadEditors());
        }
        return _results;
      };

      return Content;

    })();
  });

}).call(this);
