// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(function(reguire) {
    var SendDialog, dialog;
    dialog = require("plugins/dialog");
    return SendDialog = (function() {
      function SendDialog(closeParent) {
        this.closeParent = closeParent;
      }

      SendDialog.prototype.show = function() {
        return dialog.show(this);
      };

      SendDialog.prototype.done = function() {
        this.closeParent();
        return dialog.close(this);
      };

      return SendDialog;

    })();
  });

}).call(this);
