// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(function(require) {
    var GridHelper;
    return GridHelper = (function() {
      function GridHelper() {
        var role, roleParent, security, transformRoles, _i, _len, _ref;
        transformRoles = function(roles) {
          var parent, result, role, root, rootId, _i, _len;
          result = [];
          rootId = Math.random();
          root = {
            id: rootId,
            name: "Root"
          };
          result.push(root);
          for (_i = 0, _len = roles.length; _i < _len; _i++) {
            role = roles[_i];
            parent = ko.utils.arrayFirst(result, function(r) {
              return r.name === role.module;
            });
            if (parent == null) {
              parent = {
                id: Math.random(),
                name: role.module,
                module: "Root",
                parentId: rootId
              };
              result.push(parent);
            }
            role.parentId = parent.id;
            result.push(role);
          }
          return result;
        };
        security = require("security/security");
        this.roles = transformRoles(security.operations());
        console.log("transformed roles");
        console.log(this.roles);
        _ref = this.roles;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          role = _ref[_i];
          role.sortkey = role.name.toLowerCase();
          role.level = 0;
          roleParent = role;
          while (roleParent.parentId != null) {
            roleParent = ko.utils.arrayFirst(this.roles, function(r) {
              return r.id === roleParent.parentId;
            });
            role.sortkey = roleParent.name.toLowerCase() + "-" + role.sortkey;
            role.level++;
          }
          role.expanded = true;
        }
        this.roles.sort(function(a, b) {
          if (a.sortkey < b.sortkey) {
            return -1;
          } else if (a.sortkey > b.sortkey) {
            return 1;
          } else {
            return 0;
          }
        });
      }

      GridHelper.prototype.init = function(grid) {
        this.grid = grid;
        return $((function(_this) {
          return function() {
            var allChildrenChecked, checkbox, checked, level, prevLevel, time1, tr, _i, _len, _ref;
            allChildrenChecked = [];
            prevLevel = 0;
            time1 = new Date();
            _ref = $($("input[type=checkbox]", _this.grid).get().reverse());
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              checkbox = _ref[_i];
              checked = $(checkbox).is(":checked");
              tr = $(checkbox).parents("tr");
              if (typeof level !== "undefined" && level !== null) {
                prevLevel = level;
              }
              level = Number(tr.find("td:eq(1)").text());
              if (level < prevLevel) {
                checked = allChildrenChecked[level + 1];
                $(checkbox).prop("checked", allChildrenChecked[level + 1] === true);
                allChildrenChecked.length = level;
              }
              allChildrenChecked[level] = (function() {
                switch (allChildrenChecked[level]) {
                  case void 0:
                    return checked;
                  case true:
                    if (checked) {
                      return true;
                    } else {
                      return null;
                    }
                  case false:
                    if (!checked) {
                      return false;
                    } else {
                      return null;
                    }
                  default:
                    return null;
                }
              })();
            }
            console.log((new Date() - time1) / 1000);
            return $("input[type=checkbox]", _this.grid).click(function() {
              var itemLevel, _results;
              tr = $(this).parents("tr");
              level = tr.find("td:eq(1)").text();
              checked = $(this).is(":checked");
              _results = [];
              while ((tr = tr.next()).length) {
                itemLevel = tr.find("td:eq(1)").text();
                if (itemLevel <= level) {
                  break;
                }
                _results.push($("input[type=checkbox]", tr).prop("checked", checked));
              }
              return _results;
            });
          };
        })(this));
      };

      GridHelper.prototype.getChecked = function() {
        var checkedIds;
        checkedIds = [];
        console.log("getChecked");
        $("input[type=checkbox]", this.grid).each(function() {
          var tr;
          tr = $(this).parents("tr");
          if ($(this).is(":checked") && $("td:eq(1)", tr).text() === "2") {
            return checkedIds.push($("td:first", tr).text());
          }
        });
        return checkedIds;
      };

      GridHelper.prototype.reload = function() {
        return this.grid.trigger("reload");
      };

      GridHelper.prototype.reset = function() {
        return $("input[type=checkbox]", this.grid).each(function() {
          return $(this).attr("checked", false);
        });
      };

      GridHelper.prototype.filter = function(pattern) {
        var prevLevel, visibleByLevel;
        pattern = pattern.trim();
        visibleByLevel = [];
        prevLevel = 0;
        return $($("input[type=checkbox]", this.grid).get().reverse()).each(function() {
          var childLevel, childTr, formattedText, html, i, isLeaf, isMatched, isVisible, level, rx, tdText, text, tr;
          tr = $(this).parents("tr");
          if (typeof level !== "undefined" && level !== null) {
            prevLevel = level;
          }
          level = Number(tr.find("td:eq(1)").text());
          tdText = tr.find("td:eq(3)");
          text = tdText.text();
          rx = new RegExp("(" + pattern + ")", "i");
          isMatched = Boolean(text.match(rx));
          isLeaf = level >= prevLevel;
          if (isLeaf) {
            visibleByLevel.length = level + 1;
          }
          isVisible = isLeaf ? isMatched : isMatched || visibleByLevel[level + 1];
          if (isMatched) {
            i = (rx.exec(text)).index;
            formattedText = text.substr(0, i) + "<em>" + text.substr(i, pattern.length) + "</em>" + text.substr(i + pattern.length);
          } else {
            formattedText = text;
          }
          if ($("span+span", tdText).length) {
            $("span+span", tdText).html(formattedText);
          } else {
            html = $("span", tdText).html();
            $(">span", tdText).html(html.substr(0, html.lastIndexOf(">") + 1));
            $(">span", tdText).append($("<span>").html(formattedText));
          }
          if (isMatched && !isLeaf) {
            childTr = tr.next();
            childLevel = Number(childTr.find("td:eq(1)").text());
            while (childTr.length && childLevel > level) {
              childTr.show();
              childTr = childTr.next();
              childLevel = Number(childTr.find("td:eq(1)").text());
            }
          }
          visibleByLevel[level] = isVisible || visibleByLevel[level];
          prevLevel = level;
          return tr.toggle(isVisible);
        });
      };

      return GridHelper;

    })();
  });

}).call(this);
