// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(function(require) {
    var DuplicateMechanismConfigsViewModel, nav, security;
    require("controls/grid");
    nav = require("nav");
    security = require("security/security");
    return DuplicateMechanismConfigsViewModel = (function() {
      function DuplicateMechanismConfigsViewModel() {
        this.selectedRowId = ko.observable();
        this.isEditAllowed = ko.observable(security.isOperationAllowed(security.permissions.update, security.categories.duplicateConfiguration));
        this.isAddAllowed = ko.observable(security.isOperationAllowed(security.permissions.create, security.categories.duplicateConfiguration));
      }

      DuplicateMechanismConfigsViewModel.prototype.attached = function(view) {
        var $grid;
        $grid = findGrid(view);
        $("form", view).submit(function() {
          $grid.trigger("reload");
          return false;
        });
        return $grid.on("gridLoad selectionChange", (function(_this) {
          return function(e, row) {
            return _this.selectedRowId(row.id);
          };
        })(this));
      };

      DuplicateMechanismConfigsViewModel.prototype.create = function() {
        return nav.open({
          path: 'fraud/duplicate-mechanism/edit',
          title: "New Duplicate Mechanism Configuration",
          data: {
            editMode: true
          }
        });
      };

      DuplicateMechanismConfigsViewModel.prototype.edit = function() {
        return nav.open({
          path: 'fraud/duplicate-mechanism/edit',
          title: "Edit Duplicate Mechanism Configuration",
          data: {
            id: this.selectedRowId(),
            editMode: true
          }
        });
      };

      DuplicateMechanismConfigsViewModel.prototype.view = function() {
        return nav.open({
          path: 'fraud/duplicate-mechanism/edit',
          title: "View Duplicate Mechanism Configuration",
          data: {
            id: this.selectedRowId(),
            editMode: false
          }
        });
      };

      return DuplicateMechanismConfigsViewModel;

    })();
  });

}).call(this);
