//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFT.RegoV2.MemberWebsite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFT.RegoV2.MemberWebsite.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo.
        /// </summary>
        public static string Menu_Bingo {
            get {
                return ResourceManager.GetString("Menu_Bingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        public static string Menu_Cashier {
            get {
                return ResourceManager.GetString("Menu_Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino.
        /// </summary>
        public static string Menu_Casino {
            get {
                return ResourceManager.GetString("Menu_Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Casino.
        /// </summary>
        public static string Menu_LiveCasino {
            get {
                return ResourceManager.GetString("Menu_LiveCasino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Menu_News {
            get {
                return ResourceManager.GetString("Menu_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Information.
        /// </summary>
        public static string Menu_PlayerProfile_BalanceInformation {
            get {
                return ResourceManager.GetString("Menu_PlayerProfile_BalanceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim a Bonus.
        /// </summary>
        public static string Menu_PlayerProfile_ClaimBonus {
            get {
                return ResourceManager.GetString("Menu_PlayerProfile_ClaimBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Menu_PlayerProfile_Personal {
            get {
                return ResourceManager.GetString("Menu_PlayerProfile_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Games.
        /// </summary>
        public static string Menu_PlayerProfile_PlayGames {
            get {
                return ResourceManager.GetString("Menu_PlayerProfile_PlayGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer a Friend.
        /// </summary>
        public static string Menu_PlayerProfile_ReferFriend {
            get {
                return ResourceManager.GetString("Menu_PlayerProfile_ReferFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Menu_Promotions {
            get {
                return ResourceManager.GetString("Menu_Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Menu_Support {
            get {
                return ResourceManager.GetString("Menu_Support", resourceCulture);
            }
        }
    }
}
