// Generated by IcedCoffeeScript 108.0.9
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var ViewModel, activateDialog, activateDialogX, app, i18n, nav, security, shell;
    app = require("durandal/app");
    security = require("security/security");
    i18n = require("i18next");
    nav = require("nav");
    shell = require("shell");
    activateDialog = require("messaging/message-templates/activate-dialog");
    activateDialogX = require("controls/status-dialog");
    return ViewModel = (function(_super) {
      __extends(ViewModel, _super);

      function ViewModel() {
        ViewModel.__super__.constructor.apply(this, arguments);
        this.shell = shell;
        this.rowId = ko.observable();
        this.gridId = "#message-template-grid";
        this.canActivate = ko.observable(false);
        this.remarks = ko.observable();
        this.hasAddPermission = ko.observable(security.isOperationAllowed(security.permissions.create, security.categories.messageTemplateManager));
        this.hasEditPermission = ko.observable(security.isOperationAllowed(security.permissions.update, security.categories.messageTemplateManager));
        this.hasActivatePermission = ko.observable(security.isOperationAllowed(security.permissions.activate, security.categories.messageTemplateManager));
        this.hasViewPermission = ko.observable(security.isOperationAllowed(security.permissions.view, security.categories.messageTemplateManager));
        this.compositionComplete = (function(_this) {
          return function() {
            return $(function() {
              return $(_this.gridId).on("gridLoad selectionChange", function(e, row) {
                _this.rowId(row.id);
                return _this.canActivate(row.data.Status === "Inactive");
              });
            });
          };
        })(this);
        this.onMessageTemplateChange = (function(_this) {
          return function() {
            return $(_this.gridId).trigger("reload");
          };
        })(this);
        $(document).on("message_template_changed", this.onMessageTemplateChange);
        this.detached = (function(_this) {
          return function() {
            return $(document).off("message_template_changed", _this.onMessageTemplateChange);
          };
        })(this);
      }

      ViewModel.prototype.statusFormatter = function() {
        return i18n.t("common.statuses." + this.Status);
      };

      ViewModel.prototype.messageTypeFormatter = function() {
        return i18n.t("messageTemplates.messageTypes." + this.MessageType);
      };

      ViewModel.prototype.messageDeliveryMethodFormatter = function() {
        return i18n.t("messageTemplates.deliveryMethods." + this.MessageDeliveryMethod);
      };

      ViewModel.prototype.openAddTab = function() {
        return nav.open({
          path: "messaging/message-templates/add",
          title: i18n.t("app:common.new")
        });
      };

      ViewModel.prototype.openViewTab = function() {
        var id;
        id = this.rowId();
        if (id != null) {
          return nav.open({
            path: "messaging/message-templates/view",
            title: i18n.t("app:common.view"),
            data: {
              id: id
            }
          });
        }
      };

      ViewModel.prototype.openEditTab = function() {
        var id;
        id = this.rowId();
        if (id != null) {
          return nav.open({
            path: "messaging/message-templates/edit",
            title: i18n.t("app:common.edit"),
            data: {
              id: id
            }
          });
        }
      };

      ViewModel.prototype.openActivateDialog = function() {
        var dialog, id;
        id = this.rowId();
        if (id && this.canActivate()) {
          dialog = new activateDialog(id);
          dialog.show();
          return null;
        }
      };

      return ViewModel;

    })(require("vmGrid"));
  });

}).call(this);
