// Generated by IcedCoffeeScript 108.0.9
(function() {
  define(["nav", "i18next", "komapping"], function(nav, i18n, mapping) {
    var ViewOfflineDepositRequest;
    return ViewOfflineDepositRequest = (function() {
      function ViewOfflineDepositRequest() {
        var _ref;
        _ref = ko.observables(), this.message = _ref[0], this.username = _ref[1], this.amount = _ref[2], this.bankName = _ref[3], this.selectedBankAccount = _ref[4], this.bankAccountId = _ref[5], this.bankProvince = _ref[6], this.bankBranch = _ref[7], this.bankAccountName = _ref[8], this.bankAccountNumber = _ref[9], this.playerRemark = _ref[10], this.unverifyReason = _ref[11], this.status = _ref[12], this.transactionNumber = _ref[13], this.bonusName = _ref[14];
      }

      ViewOfflineDepositRequest.prototype.close = function() {
        return nav.close();
      };

      ViewOfflineDepositRequest.prototype.activate = function(data) {
        this.message(data.message);
        return $.get("/offlineDeposit/GetForView", {
          id: data.requestId
        }).done((function(_this) {
          return function(response) {
            mapping.fromJS(response.data, {}, _this);
            if (_this.bonusName() === null) {
              return _this.bonusName(i18n.t("common.none"));
            }
          };
        })(this));
      };

      return ViewOfflineDepositRequest;

    })();
  });

}).call(this);
